#include <errno.h>

int __crt_macos_to_bionic_errno(int error) {
  switch (error) {
    case 0:
      return 0;
    case 1:
      return EPERM;
    case 2:
      return ENOENT;
    case 3:
      return ESRCH;
    case 4:
      return EINTR;
    case 5:
      return EIO;
    case 6:
      return ENXIO;
    case 7:
      return E2BIG;
    case 8:
      return ENOEXEC;
    case 9:
      return EBADF;
    case 10:
      return ECHILD;
    case 11:
      return EDEADLK;
    case 12:
      return ENOMEM;
    case 13:
      return EACCES;
    case 14:
      return EFAULT;
    case 15:
      return ENOTBLK;
    case 16:
      return EBUSY;
    case 17:
      return EEXIST;
    case 18:
      return EXDEV;
    case 19:
      return ENODEV;
    case 20:
      return ENOTDIR;
    case 21:
      return EISDIR;
    case 22:
      return EINVAL;
    case 23:
      return ENFILE;
    case 24:
      return EMFILE;
    case 25:
      return ENOTTY;
    case 26:
      return ETXTBSY;
    case 27:
      return EFBIG;
    case 28:
      return ENOSPC;
    case 29:
      return ESPIPE;
    case 30:
      return EROFS;
    case 31:
      return EMLINK;
    case 32:
      return EPIPE;
    case 33:
      return EDOM;
    case 34:
      return ERANGE;
    case 35:
      return EAGAIN;
    case 36:
      return EINPROGRESS;
    case 37:
      return EALREADY;
    case 38:
      return ENOTSOCK;
    case 39:
      return EDESTADDRREQ;
    case 40:
      return EMSGSIZE;
    case 41:
      return EPROTOTYPE;
    case 42:
      return ENOPROTOOPT;
    case 43:
      return EPROTONOSUPPORT;
    case 44:
      return ESOCKTNOSUPPORT;
    case 45:
      return ENOTSUP;
    case 46:
      return EPFNOSUPPORT;
    case 47:
      return EAFNOSUPPORT;
    case 48:
      return EADDRINUSE;
    case 49:
      return EADDRNOTAVAIL;
    case 50:
      return ENETDOWN;
    case 51:
      return ENETUNREACH;
    case 52:
      return ENETRESET;
    case 53:
      return ECONNABORTED;
    case 54:
      return ECONNRESET;
    case 55:
      return ENOBUFS;
    case 56:
      return EISCONN;
    case 57:
      return ENOTCONN;
    case 58:
      return ESHUTDOWN;
    case 59:
      return ETOOMANYREFS;
    case 60:
      return ETIMEDOUT;
    case 61:
      return ECONNREFUSED;
    case 62:
      return ELOOP;
    case 63:
      return ENAMETOOLONG;
    case 64:
      return EHOSTDOWN;
    case 65:
      return EHOSTUNREACH;
    case 66:
      return ENOTEMPTY;
    case 67:
      return EAGAIN;
    case 68:
      return EUSERS;
    case 69:
      return EDQUOT;
    case 70:
      return ESTALE;
    case 71:
      return EREMOTE;
    case 72:
    case 73:
    case 75:
    case 76:
      return EPROTO;
    case 74:
      return ENOSYS;
    case 77:
      return ENOLCK;
    case 78:
      return ENOSYS;
    case 79:
      return EINVAL;
    case 80:
    case 81:
      return EACCES;
    case 82:
    case 83:
      return EIO;
    case 84:
      return EOVERFLOW;
    case 89:
      return ECANCELED;
    case 90:
      return EIDRM;
    case 91:
      return ENOMSG;
    case 92:
      return EILSEQ;
    case 93:
      return ENODATA;
    case 94:
      return EBADMSG;
    case 95:
      return EMULTIHOP;
    case 96:
      return ENODATA;
    case 97:
      return ENOLINK;
    case 98:
      return ENOSR;
    case 99:
      return ENOSTR;
    case 100:
      return EPROTO;
    case 101:
      return ETIME;
    case 102:
      return EOPNOTSUPP;
    case 104:
      return ENOTRECOVERABLE;
    case 105:
      return EOWNERDEAD;
    default:
      return EINVAL;
  }
}
